version: '3.1'

services:
  db:
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: user_database
      MYSQL_USER: user
      MYSQL_PASSWORD: example
      TZ: "Asia/Tokyo"
    ports:
      - 3307:3306
    volumes:
      - $PWD/sql:/docker-entrypoint-initdb.d
      - $PWD/conf/mysql:/etc/mysql/conf.d
